export  const LH = "http://192.241.138.220"


export  const BOOTCAMP_LIST_REQUEST = "BOOTCAMP_LIST_REQUEST"
export  const BOOTCAMP_LIST_SUCCESS = "BOOTCAMP_LIST_SUCCESS"
export  const BOOTCAMP_LIST_FAIL = "BOOTCAMP_LIST_FAIL"


export  const HELP_LIST_REQUEST = "HELP_LIST_REQUEST"
export  const HELP_LIST_SUCCESS = "HELP_LIST_SUCCESS"
export  const HELP_LIST_FAIL = "HELP_LIST_FAIL"


export  const PAYMENT_REQUEST = "PAYMENT_REQUEST"
export  const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
export  const PAYMENT_FAIL = "PAYMENT_FAIL"


export  const CONTACTUS_REQUEST = "CONTACTUS_REQUEST"
export  const CONTACTUS_SUCCESS = "CONTACTUS_SUCCESS"
export  const CONTACTUS_FAIL = "CONTACTUS_FAIL"

export  const SLIDER_EMAIL_REQUEST = "SLIDER_EMAIL_REQUEST"
export  const SLIDER_EMAIL_SUCCESS = "SLIDER_EMAIL_SUCCESS"
export  const SLIDER_EMAIL_FAIL = "SLIDER_EMAIL_FAIL"

